from __future__ import annotations

from typing import Optional, Dict, Any
from typing_extensions import override
from ..config.settings import Settings
from .llm import LLM
import logging
from openai import OpenAI


class DeepSeekModel(LLM):
    """
    A subclass of LLM that uses DeepSeek as the backend for text generation.
    
    Supports both standard chat and reasoning models (like deepseek-r1).
    
    Attributes:
        model_name (str): The name of the model to use with DeepSeek.
        role (str): The role of the user in the conversation, typically "user".
        system_prompt (str): The system prompt to use for text generation.
        model (OpenAI): The OpenAI-compatible client configured for DeepSeek API.
        is_reasoning_model (bool): Whether the model is a reasoning model.
    """

    def __init__(
        self,
        model_name: str,
        system_prompt: Optional[str] = None,
        system_prompt_file: Optional[str] = None,
        api_base: Optional[str] = None,
        role: str = "user",
    ) -> None:
        """
        Initializes an instance of DeepSeekModel.

        Args:
            model_name (str): The name of the model to use with DeepSeek.
            system_prompt (Optional[str]): The system prompt to use.
            system_prompt_file (Optional[str]): The path to the file to load the system prompt from.
            api_base (Optional[str]): Custom API base URL. Defaults to DeepSeek's API endpoint.
            role (str): The role of the user in the conversation, defaults to "user".
        """
        self.api_base = api_base or Settings.DEFAULT_DEEPSEEK_CLIENT
        super().__init__(model_name, system_prompt, system_prompt_file, self.api_base)
        logging.info(f"Using DeepSeek with {model_name} model 🐋")
        
        self.role: str = role
        # Check if this is a reasoning model
        self.is_reasoning_model = any(r in model_name.lower() for r in ["r1", "reasoner", "deepseek-r1"])

    @override
    def load(self) -> OpenAI:
        """
        Loads the OpenAI-compatible client configured for DeepSeek API.

        Returns:
            OpenAI: The client object to interact with DeepSeek.
        """
        return OpenAI(
            base_url=Settings.DEFAULT_DEEPSEEK_CLIENT,
            api_key=Settings.DEEPSEEK_API_KEY
        )

    @override
    def generate(self, input: Dict[str, Any]) -> str:
        """
        Generates text using the DeepSeek model.
        
        For reasoning models, extracts reasoning content if available.

        Args:
            input (Dict[str, Any]): The input data for text generation.

        Returns:
            str: The text generated by the model.
        """
        messages = []
        
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})
        
        # Handle text content
        content = input.get("question", "")
        
        # Handle images if present (DeepSeek V3 supports vision)
        if "images" in input and input["images"]:
            content_blocks = [{"type": "text", "text": content}]
            for image in input["images"]:
                try:
                    content_blocks.append({
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{image['base64']}"
                        }
                    })
                except Exception as e:
                    logging.error(f"Could not process image: {e}")
            
            messages.append({"role": self.role, "content": content_blocks})
        else:
            messages.append({"role": self.role, "content": content})
        
        # For reasoning models, use appropriate parameters
        kwargs = {
            "model": self.model_name,
            "messages": messages,
        }
        
        # Reasoning models may have different max tokens behavior
        if self.is_reasoning_model:
            kwargs["max_tokens"] = 8192  # Reasoning models may need more tokens
        
        response = self.model.chat.completions.create(**kwargs)
        
        result = response.choices[0].message.content
        
        # For reasoning models, try to extract reasoning if available
        if self.is_reasoning_model:
            reasoning = getattr(response.choices[0].message, 'reasoning_content', None)
            if reasoning:
                # Wrap reasoning in think tags for consistency
                result = f"<think>{reasoning}</think>\n\n{result}"
        
        return result

    def generate_with_thinking(self, input: Dict[str, Any]) -> Dict[str, str]:
        """
        Generate text and return both the final answer and reasoning (if available).
        
        This is especially useful for DeepSeek R1 and other reasoning models.

        Args:
            input (Dict[str, Any]): The input data for text generation.

        Returns:
            Dict[str, str]: Dictionary containing 'answer' and optionally 'reasoning'.
        """
        messages = []
        
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})
        
        messages.append({"role": self.role, "content": input.get("question", "")})
        
        response = self.model.chat.completions.create(
            model=self.model_name,
            messages=messages,
        )
        
        message = response.choices[0].message
        result = {
            "answer": message.content,
            "reasoning": getattr(message, 'reasoning_content', None)
        }
        
        return result
