from __future__ import annotations

from typing import Optional, Dict, Any
from typing_extensions import override
from ..config.settings import Settings
from .llm import LLM
import logging
from openai import OpenAI


class KimiModel(LLM):
    """
    A subclass of LLM that uses Kimi (Moonshot AI) as the backend for text generation.
    
    Attributes:
        model_name (str): The name of the model to use with Kimi.
        role (str): The role of the user in the conversation, typically "user".
        system_prompt (str): The system prompt to use for text generation.
        model (OpenAI): The OpenAI-compatible client configured for Kimi API.
    """

    def __init__(
        self,
        model_name: str,
        system_prompt: Optional[str] = None,
        system_prompt_file: Optional[str] = None,
        api_base: Optional[str] = None,
        role: str = "user",
    ) -> None:
        """
        Initializes an instance of KimiModel.

        Args:
            model_name (str): The name of the model to use with Kimi.
            system_prompt (Optional[str]): The system prompt to use.
            system_prompt_file (Optional[str]): The path to the file to load the system prompt from.
            api_base (Optional[str]): Custom API base URL. Defaults to Kimi's API endpoint.
            role (str): The role of the user in the conversation, defaults to "user".
        """
        self.api_base = api_base or Settings.DEFAULT_KIMI_CLIENT
        super().__init__(model_name, system_prompt, system_prompt_file, self.api_base)
        logging.info(f"Using Kimi with {model_name} model 🌙")

        self.role: str = role

    @override
    def load(self) -> OpenAI:
        """
        Loads the OpenAI-compatible client configured for Kimi API.

        Returns:
            OpenAI: The client object to interact with Kimi.
        """
        return OpenAI(
            base_url=Settings.DEFAULT_KIMI_CLIENT,
            api_key=Settings.KIMI_API_KEY
        )

    @override
    def generate(self, input: Dict[str, Any]) -> str:
        """
        Generates text using the Kimi model.

        Args:
            input (Dict[str, Any]): The input data for text generation.

        Returns:
            str: The text generated by the model.
        """
        messages = []
        
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})
        
        # Handle text content
        content = input.get("question", "")
        
        # Handle images if present (Kimi supports vision)
        if "images" in input and input["images"]:
            content_blocks = [{"type": "text", "text": content}]
            for image in input["images"]:
                try:
                    content_blocks.append({
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{image['base64']}"
                        }
                    })
                except Exception as e:
                    logging.error(f"Could not process image: {e}")
            
            messages.append({"role": self.role, "content": content_blocks})
        else:
            messages.append({"role": self.role, "content": content})
        
        response = self.model.chat.completions.create(
            model=self.model_name,
            messages=messages,
        )
        
        return response.choices[0].message.content
